"""
Forecast U.S. real GDP with external regressors.

Dataset citation:
    This script uses the publicly available `macrodata` dataset bundled with
    statsmodels. It contains U.S. quarterly macroeconomic observations from
    1959Q1 through 2009Q3 and is documented at:
    https://www.statsmodels.org/stable/datasets/generated/macrodata.html

Deliverables generated by this script:
    - forecasting_plot.png
    - performance_report.txt
"""

from __future__ import annotations

import warnings
from dataclasses import dataclass
from pathlib import Path

import matplotlib.pyplot as plt
import numpy as np
import pandas as pd
import statsmodels.api as sm
from sklearn.metrics import mean_absolute_error, mean_squared_error
from sklearn.preprocessing import StandardScaler
from statsmodels.tsa.statespace.sarimax import SARIMAX


try:
    OUTPUT_DIR = Path(__file__).resolve().parent
except NameError:
    OUTPUT_DIR = Path.cwd()
PLOT_PATH = OUTPUT_DIR / "forecasting_plot.png"
REPORT_PATH = OUTPUT_DIR / "performance_report.txt"
TEST_SIZE = 24
FUTURE_STEPS = 8
REGRESSOR_COLUMNS = ["unemp", "realint", "infl"]


@dataclass
class ModelChoice:
    order: tuple[int, int, int]
    seasonal_order: tuple[int, int, int, int]
    aic: float
    result: object


def load_macrodata() -> pd.DataFrame:
    """Load and index the public quarterly macroeconomic dataset."""
    data = sm.datasets.macrodata.load_pandas().data.copy()
    period_labels = (
        data["year"].astype(int).astype(str)
        + "Q"
        + data["quarter"].astype(int).astype(str)
    )
    periods = pd.PeriodIndex(period_labels, freq="Q")
    data["period"] = periods
    data["date"] = periods.to_timestamp(how="end").normalize()
    data = data.sort_values("date").set_index("date")
    return data


def cap_outliers_iqr(data: pd.DataFrame, columns: list[str]) -> pd.DataFrame:
    """Winsorize extreme values using 1.5*IQR limits."""
    cleaned = data.copy()
    for column in columns:
        q1 = cleaned[column].quantile(0.25)
        q3 = cleaned[column].quantile(0.75)
        iqr = q3 - q1
        lower = q1 - 1.5 * iqr
        upper = q3 + 1.5 * iqr
        cleaned[column] = cleaned[column].clip(lower=lower, upper=upper)
    return cleaned


def preprocess(data: pd.DataFrame) -> pd.DataFrame:
    """Prepare numeric data, repair missing values, and cap outliers."""
    numeric_columns = ["realgdp", *REGRESSOR_COLUMNS]
    cleaned = data.copy()
    for column in numeric_columns:
        cleaned[column] = pd.to_numeric(cleaned[column], errors="coerce")

    full_periods = pd.period_range(
        cleaned["period"].iloc[0], cleaned["period"].iloc[-1], freq="Q"
    )
    full_dates = full_periods.to_timestamp(how="end").normalize()
    cleaned = cleaned.reindex(full_dates)
    cleaned["period"] = full_periods
    cleaned[numeric_columns] = (
        cleaned[numeric_columns]
        .interpolate(method="linear")
        .ffill()
        .bfill()
    )
    cleaned = cap_outliers_iqr(cleaned, numeric_columns)
    return cleaned


def build_model_frame(data: pd.DataFrame) -> pd.DataFrame:
    """Create target and external-regressor features for SARIMAX."""
    model_data = data[["period", "realgdp", *REGRESSOR_COLUMNS]].copy()
    model_data["log_realgdp"] = np.log(model_data["realgdp"])
    for column in REGRESSOR_COLUMNS:
        model_data[f"{column}_lag1"] = model_data[column].shift(1)
    return model_data.dropna()


def fit_sarimax_grid(
    y_train: pd.Series, x_train: pd.DataFrame
) -> tuple[ModelChoice, pd.DataFrame]:
    """Fit a compact SARIMAX grid and select the lowest-AIC model."""
    candidate_orders = [(1, 1, 0), (0, 1, 1), (1, 1, 1), (2, 1, 1)]
    candidate_seasonal_orders = [
        (0, 0, 0, 0),
        (1, 0, 0, 4),
        (0, 1, 1, 4),
    ]
    best_choice: ModelChoice | None = None
    search_rows: list[dict[str, object]] = []

    for order in candidate_orders:
        for seasonal_order in candidate_seasonal_orders:
            try:
                with warnings.catch_warnings():
                    warnings.simplefilter("ignore")
                    result = SARIMAX(
                        y_train,
                        exog=x_train,
                        order=order,
                        seasonal_order=seasonal_order,
                        trend="c",
                        enforce_stationarity=False,
                        enforce_invertibility=False,
                    ).fit(disp=False, maxiter=500)
                aic = float(result.aic)
                search_rows.append(
                    {
                        "order": order,
                        "seasonal_order": seasonal_order,
                        "aic": aic,
                    }
                )
                if best_choice is None or aic < best_choice.aic:
                    best_choice = ModelChoice(order, seasonal_order, aic, result)
            except Exception as exc:  # Some parameter combinations can be unstable.
                search_rows.append(
                    {
                        "order": order,
                        "seasonal_order": seasonal_order,
                        "aic": np.nan,
                        "error": str(exc),
                    }
                )

    if best_choice is None:
        raise RuntimeError("No SARIMAX model could be fitted.")
    search_results = pd.DataFrame(search_rows).sort_values("aic", na_position="last")
    return best_choice, search_results


def prediction_frame(forecast_result: object) -> pd.DataFrame:
    """Convert log-scale forecasts and confidence intervals back to GDP scale."""
    predicted_log = forecast_result.predicted_mean
    interval_log = forecast_result.conf_int(alpha=0.05)
    frame = pd.DataFrame(
        {
            "prediction": np.exp(predicted_log),
            "lower": np.exp(interval_log.iloc[:, 0]),
            "upper": np.exp(interval_log.iloc[:, 1]),
        },
        index=predicted_log.index,
    )
    return frame


def evaluate(actual: pd.Series, predicted: pd.Series) -> dict[str, float]:
    rmse = float(np.sqrt(mean_squared_error(actual, predicted)))
    mae = float(mean_absolute_error(actual, predicted))
    mape = float(np.mean(np.abs((actual - predicted) / actual)) * 100)
    return {"RMSE": rmse, "MAE": mae, "MAPE": mape}


def project_future_regressors(history: pd.DataFrame, steps: int) -> pd.DataFrame:
    """Project future exogenous variables using recent 8-quarter drift."""
    recent = history[REGRESSOR_COLUMNS].tail(8)
    drift = (recent.iloc[-1] - recent.iloc[0]) / max(len(recent) - 1, 1)
    bounds = history[REGRESSOR_COLUMNS].quantile([0.05, 0.95])
    current = history[REGRESSOR_COLUMNS].iloc[-1].to_dict()
    last_period = history["period"].iloc[-1]
    future_periods = pd.period_range(last_period + 1, periods=steps, freq="Q")
    rows: list[dict[str, float | pd.Period]] = []

    for period in future_periods:
        next_values: dict[str, float] = {}
        for column in REGRESSOR_COLUMNS:
            lower = bounds.loc[0.05, column]
            upper = bounds.loc[0.95, column]
            next_values[column] = float(
                np.clip(current[column] + drift[column], lower, upper)
            )

        row: dict[str, float | pd.Period] = {"period": period, **next_values}
        for column in REGRESSOR_COLUMNS:
            row[f"{column}_lag1"] = float(current[column])
        rows.append(row)
        current = next_values

    future_dates = future_periods.to_timestamp(how="end").normalize()
    return pd.DataFrame(rows, index=future_dates)


def make_plot(
    model_data: pd.DataFrame,
    test_predictions: pd.DataFrame,
    future_predictions: pd.DataFrame,
    train_end: pd.Timestamp,
) -> None:
    plt.style.use("seaborn-v0_8-whitegrid")
    fig, ax = plt.subplots(figsize=(12, 7))

    ax.plot(
        model_data.index,
        model_data["realgdp"],
        color="#1f2937",
        linewidth=2,
        label="Actual real GDP",
    )
    ax.plot(
        test_predictions.index,
        test_predictions["prediction"],
        color="#2563eb",
        linewidth=2,
        label="Held-out prediction",
    )
    ax.fill_between(
        test_predictions.index,
        test_predictions["lower"],
        test_predictions["upper"],
        color="#60a5fa",
        alpha=0.22,
        label="Held-out 95% interval",
    )
    ax.plot(
        future_predictions.index,
        future_predictions["prediction"],
        color="#dc2626",
        linewidth=2,
        label="Future forecast",
    )
    ax.fill_between(
        future_predictions.index,
        future_predictions["lower"],
        future_predictions["upper"],
        color="#f87171",
        alpha=0.24,
        label="Future 95% interval",
    )

    ax.axvline(train_end, color="#6b7280", linestyle="--", linewidth=1)
    ax.axvline(model_data.index[-1], color="#9ca3af", linestyle=":", linewidth=1)
    ax.set_title("U.S. Real GDP Forecast with External Regressors", fontsize=15)
    ax.set_xlabel("Quarter")
    ax.set_ylabel("Real GDP")
    ax.legend(loc="upper left")
    fig.tight_layout()
    fig.savefig(PLOT_PATH, dpi=160)
    plt.close(fig)


def write_report(
    metrics: dict[str, float],
    best_choice: ModelChoice,
    search_results: pd.DataFrame,
    train: pd.DataFrame,
    test: pd.DataFrame,
    future_predictions: pd.DataFrame,
) -> None:
    lines = [
        "Time Series Forecasting Performance Report",
        "==========================================",
        "",
        "Dataset: statsmodels macrodata, public U.S. quarterly macroeconomic data",
        "Source: https://www.statsmodels.org/stable/datasets/generated/macrodata.html",
        "Target: realgdp, modeled on the log scale and converted back for reporting",
        f"External regressors: {', '.join(REGRESSOR_COLUMNS)} plus one-quarter lags",
        "",
        "Preprocessing:",
        "- Coerced modeling columns to numeric dtype.",
        "- Reindexed to a complete quarterly timeline.",
        "- Filled missing values with linear interpolation plus forward/backward fill.",
        "- Capped numeric outliers using 1.5*IQR winsorization.",
        "",
        "Model:",
        f"- Selected SARIMAX order: {best_choice.order}",
        f"- Selected seasonal order: {best_choice.seasonal_order}",
        f"- Selected training AIC: {best_choice.aic:,.3f}",
        "- Model parameters were refined with a compact SARIMAX grid search.",
        "- Future external regressors were projected with recent 8-quarter drift and bounded by historical 5th/95th percentiles.",
        "",
        "Train/Test Split:",
        f"- Training period: {train.index[0].date()} to {train.index[-1].date()} ({len(train)} quarters)",
        f"- Test period: {test.index[0].date()} to {test.index[-1].date()} ({len(test)} quarters)",
        "",
        "Evaluation Metrics on Held-Out Test Set:",
        f"- RMSE: {metrics['RMSE']:,.3f}",
        f"- MAE: {metrics['MAE']:,.3f}",
        f"- MAPE: {metrics['MAPE']:,.3f}%",
        "",
        "Future Forecast:",
        f"- Forecast period: {future_predictions.index[0].date()} to {future_predictions.index[-1].date()} ({len(future_predictions)} quarters)",
        f"- Plot file: {PLOT_PATH.name}",
        "",
        "Top Grid Search Results:",
        search_results.head(5).to_string(index=False),
        "",
    ]
    REPORT_PATH.write_text("\n".join(lines), encoding="utf-8")


def main() -> None:
    raw_data = load_macrodata()
    cleaned_data = preprocess(raw_data)
    model_data = build_model_frame(cleaned_data)

    feature_columns = REGRESSOR_COLUMNS + [f"{column}_lag1" for column in REGRESSOR_COLUMNS]
    train = model_data.iloc[:-TEST_SIZE].copy()
    test = model_data.iloc[-TEST_SIZE:].copy()

    scaler = StandardScaler()
    x_train = pd.DataFrame(
        scaler.fit_transform(train[feature_columns]),
        index=train.index,
        columns=feature_columns,
    )
    x_test = pd.DataFrame(
        scaler.transform(test[feature_columns]),
        index=test.index,
        columns=feature_columns,
    )
    y_train = train["log_realgdp"]
    y_test = test["log_realgdp"]

    best_choice, search_results = fit_sarimax_grid(y_train, x_train)
    test_forecast = best_choice.result.get_forecast(steps=len(test), exog=x_test)
    test_predictions = prediction_frame(test_forecast)
    metrics = evaluate(test["realgdp"], test_predictions["prediction"])

    final_scaler = StandardScaler()
    x_all = pd.DataFrame(
        final_scaler.fit_transform(model_data[feature_columns]),
        index=model_data.index,
        columns=feature_columns,
    )
    with warnings.catch_warnings():
        warnings.simplefilter("ignore")
        final_result = SARIMAX(
            model_data["log_realgdp"],
            exog=x_all,
            order=best_choice.order,
            seasonal_order=best_choice.seasonal_order,
            trend="c",
            enforce_stationarity=False,
            enforce_invertibility=False,
        ).fit(disp=False, maxiter=500)

    future_exog = project_future_regressors(cleaned_data, FUTURE_STEPS)
    x_future = pd.DataFrame(
        final_scaler.transform(future_exog[feature_columns]),
        index=future_exog.index,
        columns=feature_columns,
    )
    future_forecast = final_result.get_forecast(steps=FUTURE_STEPS, exog=x_future)
    future_predictions = prediction_frame(future_forecast)

    make_plot(model_data, test_predictions, future_predictions, train.index[-1])
    write_report(metrics, best_choice, search_results, train, test, future_predictions)

    print(f"Wrote {PLOT_PATH}")
    print(f"Wrote {REPORT_PATH}")
    print(
        "Held-out metrics: "
        f"RMSE={metrics['RMSE']:,.3f}, "
        f"MAE={metrics['MAE']:,.3f}, "
        f"MAPE={metrics['MAPE']:,.3f}%"
    )


if __name__ == "__main__":
    main()
